def verify_object_match(self, actual_obj: Any, expected_obj: Any) -> Tuple[bool, str]:
    """
    Verify that two complex Python objects are deeply identical.

    This function recursively checks nested layers of dictionaries, lists,
    sets, and custom objects to confirm all keys and values match.

    :param actual_obj: The actual object generated by the application.
    :param expected_obj: The expected object containing baseline values.
    :return: A tuple containing a success boolean and a failure reason string.
    """
    """
    Deeply compares two Python objects, including dictionaries, lists, and custom classes.
    Returns (True, "") if equal, or (False, "Reason why") if different.
    """
    # 1. Check if they have the same data type
    if type(actual_obj) != type(expected_obj):
        return (
            False,
            f"Type mismatch: {type(actual_obj).name} vs {type(expected_obj).name}",
        )

    # 2. Compare Dictionaries
    if isinstance(actual_obj, dict):
        if len(actual_obj) != len(expected_obj):
            return (
                False,
                f"Dict size mismatch: {len(actual_obj)} items vs {len(expected_obj)} items",
            )
        for key in actual_obj:
            if key not in expected_obj:
                return False, f"Key '{key}' is missing in the second object"
            is_match, reason = self.verify_object_match(
                actual_obj=actual_obj[key], expected_obj=expected_obj[key]
            )
            if not is_match:
                return False, f".{key} -> {reason}"
        return True, ""

    # 3. Compare Lists or Tuples
    elif isinstance(actual_obj, (list, tuple)):
        if len(actual_obj) != len(expected_obj):
            return False, f"List length mismatch: {len(actual_obj)} vs {len(expected_obj)}"
        for index, (item1, item2) in enumerate(zip(actual_obj, expected_obj)):
            is_match, reason = self.verify_object_match(actual_obj=item1, expected_obj=item2)
            if not is_match:
                return False, f"[{index}] -> {reason}"
        return True, ""

    # 4. Compare Sets
    elif isinstance(actual_obj, set):
        if actual_obj != expected_obj:
            return False, "Sets do not have the same items"
        return True, ""

    # 5. Compare Custom Class Objects (checks their variables)
    elif hasattr(actual_obj, "dict") and hasattr(expected_obj, "dict"):
        return self.verify_object_match(
            actual_obj=actual_obj.dict, expected_obj=expected_obj.dict
        )

    # 6. Compare Simple Values (Strings, Numbers, Booleans)
    else:
        if actual_obj != expected_obj:
            return False, f"Value mismatch: {actual_obj} != {expected_obj}"
        return True, ""
